markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Mike Grassotti
# url: http://zachholman.com
description: A fantastic blog that is fantastic.
twitter: mgrassotti
github: mikegrassotti
gravatar_url: http://gravatar.com/avatar/9b9536f792ccd2b3641d8e3f9a157167